server:
  port: 3001
  servlet:
    context-path: /api
  error:
    include-stacktrace: always

spring:
  security:
    oauth2:
      client:
        provider:
          zitadel:
            issuerUri: https://issuer.zitadel.ch
            user-name-attribute: preferred_username
        registration:
          zitadel:
            client-id: '220115371552735489@demo'
            client-secret: '220115371552735489@demo' # TODO: Replace with your client secret
            client-authentication-method: client_secret_post
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: ["openid", "profile"]

logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug